### ISSUE TITLE
trailing slash in backend URL argument causes failure

### ISSUE THREAD

**Issue by pvnovarese** [sysdiglabs/secure-inline-scan#10]
if I put a trailing slash on the backend URL with the -s option (e.g. **https://secure.sysdig.com/** ), I get a unhelpful failure message:

```
pvn@gyarados> ./inline_scan.sh analyze -s https://secure.sysdig.com/ -k (token redacted) hello-world:latest

Using local image for scanning -- docker.io/anchore/inline-scan:v0.5.0

	ERROR - unable to fetch account information from anchore-engine for specified user

***SERVICE RESPONSE****

<a href="/api/scanning/v1/anchore/account">Moved Permanently</a>.


***END SERVICE RESPONSE****
```

Works as intended without the trailing slash:

```
pvn@gyarados> ./inline_scan.sh analyze -s https://secure.sysdig.com -k (token redacted) hello-world:latest

Using local image for scanning -- docker.io/anchore/inline-scan:v0.5.0
Saving hello-world:latest for local analysis
Successfully prepared image archive -- /tmp/sysdig/hello-world:latest.tar

Analyzing hello-world:latest...

...

Status is pass

Cleaning up docker container: 97d1fd02a6fee3791efb9b79ea972b2a642b1f96ccbb0bbeb57a949f81b61662
```

essentially the problem is that the script tries to hit https://secure.sysdig.com//api/scanning/v1/anchore instead of https://secure.sysdig.com/api/scanning/v1/anchore

I'm not really sure if it would be better to just check for this when the other options are checked and give a better, specific error message or to just parse the argument and remove a trailing slash (it seems like this might cause other problems in some corner case I'm unable to imagine, though), or if there is some better way to handle it.

**Comment by yathi-sysdig** [comment]
@haresh-suresh  Please take a look.

**Comment by haresh-suresh** [comment]
@pvnovarese This is being addressed as part of new enhancements, that is targeted for release sometime next week. There will be a more clear error message displayed for this, at the validation step itself.

**Comment by pvnovarese** [comment]
OK I'll close this for now and wait for the update :)
