### ISSUE TITLE
Add considering On-prem URL 

### ISSUE THREAD

**Issue by ukitazume** [sysdiglabs/secure-inline-scan#21]
the command output shows only SaaS Sysdig even if they provide the on-prem URL.  
Could you show the full result with `-s` option value?

```
View the full result @ https://secure.sysdig.com/#/scanning/scan-results/docker.io%2Falpine%3A3.10/sha256:7c3773f7bcc969f03f8f653910001d99a9d324b4b9caa008846ad2c3089f5a5f/summaries
PDF report of the scan results can be generated with -R option.
```

**Comment by haresh-suresh** [comment]
This should be addressed in this PR here : https://github.com/sysdiglabs/secure-inline-scan/pull/22 .
Thanks for catching it !
