### ISSUE TITLE
Sysdig token printed to screen

### ISSUE THREAD

**Issue by dylanzt** [sysdiglabs/secure-inline-scan#56]
At https://github.com/sysdiglabs/secure-inline-scan/blob/master/inline_scan.sh#L174, the script prints the Sysdig token to stderr. We're running this as part of our CICD, so it would be preferable to not leak the token to terminal.

**Comment by airadier** [comment]
This should be resolved in commit https://github.com/sysdiglabs/secure-inline-scan/commit/4a7c986e5f893b766e09ca6516d4b2286667dce8

@ProvoK can you confirm so we can close this issue?

**Comment by dylanzt** [comment]
Hey @airadier, I'm happy to close this myself, that commit makes the same change we've got in our local build of this image.
