### ISSUE TITLE
get_and_validate_analyzer_options function takes excessive amount of time to complete

### ISSUE THREAD

**Issue by JordanSussman** [sysdiglabs/secure-inline-scan#62]
I recently started testing the [inline_scan.sh script](https://github.com/sysdiglabs/secure-inline-scan/blob/master/inline_scan.sh), and noticed that the [get_and_validate_analyzer_options function](https://github.com/sysdiglabs/secure-inline-scan/blob/master/inline_scan.sh#L118) is often taking >= 45 seconds to complete, thus it is a large percentage of the overall time. Steps to reproduce the behavior I am seeing:

1. Copy the script locally
1. Add some date statements in the script to determine how long each function is taking
1. Run `./inline_scan.sh analyze -s https://secure.sysdig.com -k <token> -P docker.io/alpine:3.10`
1. See that the get_and_validate_analyzer_options function takes excessively long for the processing it does.

We are particularly trying to optimize for the fastest execution times to reduce the burden for our internal developers.

**Comment by JordanSussman** [comment]
Further troubleshooting indicates that https://github.com/sysdiglabs/secure-inline-scan/blob/master/inline_scan.sh#L170 is causing the problem since that particular API endpoint takes a long time to return for our account. The response times I captured with curl looks like:

```
curl --write-out "%{http_code},%{time_total},%{time_connect},%{time_appconnect},%{time_starttransfer}\n" -k -s --fail -H "Authorization: Bearer ${SYSDIG_API_TOKEN}" https://secure.sysdig.com/api/scanning/v1/anchore/images
200,47.581980,0.053996,0.103724,40.284750
```

**Comment by ProvoK** [comment]
Hi @JordanSussman 

Thank you very much for spotting this and for the detailed analysis!

I'll assign this issue to me and provide a PR soon
