### ISSUE TITLE
CloudFront error when uploading files for scanning

### ISSUE THREAD

**Issue by marcredhat** [sysdiglabs/secure-inline-scan#9]
Hi,

export POST_CALL_RETRIES=5
export SYSDIG_SCANNING_URL="https://secure.sysdig.com"
export SYSDIG_API_TOKEN=mytoken
export analysis_archive_name="hello-2.10.tar.gz"
sudo curl -sSk  -X POST  -H "Content-Type: multipart/form-data" -H "Authorization: Bearer ${SYSDIG_API_TOKEN}" -F "archive_file=@/tmp/sysdig/${analysis_archive_name}" "${SYSDIG_SCANNING_URL}/import/images"

results in "This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests." (full CloudFront response below)

Same results with GET and PUT.

ERROR: The request could not be satisfied
403 ERROR
The request could not be satisfied.
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.

Generated by cloudfront (CloudFront)
Request ID: BWpkDNjoxAcD6UBBzbyGHiSBQn4KJBfuucObJf-VgR5YrgEgh004TA==

**Comment by yathi-sysdig** [comment]
We are looking into this issue. It has to do with some of the timeouts we have internally. We are evaluating a fix currently.

**Comment by yathi-sysdig** [comment]
This should be fixed now. Closing the ticket. Reopen if you see 504's again.
